import sqlite3

SQL_CREATE = """
CREATE TABLE IF NOT EXISTS search_keywords (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    category TEXT NOT NULL CHECK(category IN ('minimal', 'standard', 'full', 'correction')),
    keyword TEXT NOT NULL,
    match_type TEXT NOT NULL DEFAULT 'exact' CHECK(match_type IN ('exact', 'contains')),
    lang TEXT NOT NULL DEFAULT 'zh' CHECK(lang IN ('zh', 'en')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(category, keyword, match_type, lang)
);
"""

SQL_INDEX = """
CREATE INDEX IF NOT EXISTS idx_sk_category ON search_keywords(category);
"""

SEED_DATA = [
    ("minimal", "你好", "exact", "zh"),
    ("minimal", "你好呀", "exact", "zh"),
    ("minimal", "你好啊", "exact", "zh"),
    ("minimal", "您好", "exact", "zh"),
    ("minimal", "好", "exact", "zh"),
    ("minimal", "嗯", "exact", "zh"),
    ("minimal", "哦", "exact", "zh"),
    ("minimal", "嗨", "exact", "zh"),
    ("minimal", "好的", "exact", "zh"),
    ("minimal", "是的", "exact", "zh"),
    ("minimal", "好吧", "exact", "zh"),
    ("minimal", "好的吧", "exact", "zh"),
    ("minimal", "嗯嗯", "exact", "zh"),
    ("minimal", "知道", "exact", "zh"),
    ("minimal", "知道了", "exact", "zh"),
    ("minimal", "明白", "exact", "zh"),
    ("minimal", "明白了", "exact", "zh"),
    ("minimal", "收到", "exact", "zh"),
    ("minimal", "谢谢", "exact", "zh"),
    ("minimal", "谢了", "exact", "zh"),
    ("minimal", "多谢", "exact", "zh"),
    ("minimal", "继续", "exact", "zh"),
    ("minimal", "来吧", "exact", "zh"),
    ("minimal", "没事", "exact", "zh"),
    ("minimal", "算了", "exact", "zh"),
    ("minimal", "没关系", "exact", "zh"),
    ("minimal", "好的谢谢", "exact", "zh"),
    ("minimal", "行", "exact", "zh"),
    ("minimal", "对", "exact", "zh"),
    ("minimal", "可以", "exact", "zh"),
    ("minimal", "成", "exact", "zh"),
    ("minimal", "行吧", "exact", "zh"),
    ("minimal", "不用干预", "exact", "zh"),
    ("minimal", "开始吧", "exact", "zh"),
    ("minimal", "你继续", "exact", "zh"),
    ("minimal", "继续吧", "exact", "zh"),
    ("minimal", "不用了", "exact", "zh"),
    ("minimal", "就这样", "exact", "zh"),
    ("minimal", "懂了", "exact", "zh"),
    ("minimal", "了解了", "exact", "zh"),
    ("minimal", "没问题", "exact", "zh"),
    ("minimal", "好嘞", "exact", "zh"),
    ("minimal", "okok", "exact", "zh"),
    ("minimal", "👌", "exact", "zh"),
    ("minimal", "👍", "exact", "zh"),
    ("minimal", "了解", "exact", "zh"),
    ("minimal", "okk", "exact", "zh"),
    ("minimal", "hi", "exact", "en"),
    ("minimal", "hello", "exact", "en"),
    ("minimal", "hey", "exact", "en"),
    ("minimal", "ok", "exact", "en"),
    ("minimal", "okay", "exact", "en"),
    ("minimal", "thanks", "exact", "en"),
    ("minimal", "thankyou", "exact", "en"),
    ("minimal", "yes", "exact", "en"),
    ("minimal", "yeah", "exact", "en"),
    ("minimal", "sure", "exact", "en"),
    ("minimal", "great", "exact", "en"),
    ("minimal", "gotit", "exact", "en"),
    ("minimal", "anyway", "exact", "en"),
    ("minimal", "alright", "exact", "en"),
    ("minimal", "cool", "exact", "en"),
    ("minimal", "np", "exact", "en"),
    ("minimal", "nvm", "exact", "en"),
    ("minimal", "fine", "exact", "en"),
    ("minimal", "gotcha", "exact", "en"),
    ("minimal", "yep", "exact", "en"),
    ("minimal", "nope", "exact", "en"),
    ("minimal", "idk", "exact", "en"),
    ("standard", "什么", "contains", "zh"),
    ("standard", "怎么", "contains", "zh"),
    ("standard", "哪里", "contains", "zh"),
    ("standard", "哪个", "contains", "zh"),
    ("standard", "哪些", "contains", "zh"),
    ("standard", "多少", "contains", "zh"),
    ("standard", "是谁", "contains", "zh"),
    ("standard", "什么时候", "contains", "zh"),
    ("standard", "为什么", "contains", "zh"),
    ("standard", "如何", "contains", "zh"),
    ("standard", "what", "contains", "en"),
    ("standard", "where", "contains", "en"),
    ("standard", "which", "contains", "en"),
    ("standard", "who", "contains", "en"),
    ("standard", "when", "contains", "en"),
    ("standard", "how many", "contains", "en"),
    ("full", "不对", "contains", "zh"),
    ("full", "错了", "contains", "zh"),
    ("full", "不是这样", "contains", "zh"),
    ("full", "你记错", "contains", "zh"),
    ("full", "记错了", "contains", "zh"),
    ("full", "纠正", "contains", "zh"),
    ("full", "应该是", "contains", "zh"),
    ("full", "怎么回事", "contains", "zh"),
    ("full", "什么原因", "contains", "zh"),
    ("full", "具体", "contains", "zh"),
    ("full", "详细", "contains", "zh"),
    ("full", "查一下", "contains", "zh"),
    ("full", "搜一下", "contains", "zh"),
    ("full", "区别", "contains", "zh"),
    ("full", "对比", "contains", "zh"),
    ("full", "步骤", "contains", "zh"),
    ("full", "流程", "contains", "zh"),
    ("full", "原理", "contains", "zh"),
    ("full", "报错", "contains", "zh"),
    ("full", "排查", "contains", "zh"),
    ("full", "配置", "contains", "zh"),
    ("full", "解决方案", "contains", "zh"),
    ("full", "wrong", "contains", "en"),
    ("full", "incorrect", "contains", "en"),
    ("full", "actually", "contains", "en"),
    ("full", "wait", "contains", "en"),
    ("full", "why", "contains", "en"),
    ("full", "how", "contains", "en"),
    ("full", "explain", "contains", "en"),
    ("full", "specifically", "contains", "en"),
    ("full", "difference", "contains", "en"),
    ("full", "compare", "contains", "en"),
    ("full", "error", "contains", "en"),
    ("full", "issue", "contains", "en"),
    ("full", "debug", "contains", "en"),
    ("full", "configure", "contains", "en"),
    ("full", "setup", "contains", "en"),
    ("full", "tutorial", "contains", "en"),
    ("correction", "不对", "contains", "zh"),
    ("correction", "不是这样", "contains", "zh"),
    ("correction", "你记错", "contains", "zh"),
    ("correction", "记错了", "contains", "zh"),
    ("correction", "说错了", "contains", "zh"),
    ("correction", "应该是", "contains", "zh"),
    ("correction", "纠正", "contains", "zh"),
    ("correction", "我说的是", "contains", "zh"),
    ("correction", "no", "exact", "en"),
    ("correction", "wrong", "exact", "en"),
    ("correction", "incorrect", "contains", "en"),
    ("correction", "actually", "exact", "en"),
    ("correction", "not really", "contains", "en"),
    ("correction", "mistake", "contains", "en"),
    ("correction", "不是", "contains", "zh"),
    ("correction", "错了", "contains", "zh"),
    ("correction", "搞错了", "contains", "zh"),
    ("correction", "弄错了", "contains", "zh"),
    ("correction", "记混了", "contains", "zh"),
    ("correction", "上次说的是", "contains", "zh"),
    ("correction", "之前说过", "contains", "zh"),
    ("correction", "你说错了", "contains", "zh"),
    ("correction", "不是吧", "contains", "zh"),
    ("correction", "i thought", "contains", "en"),
    ("correction", "i meant", "contains", "en"),
    ("correction", "you said", "contains", "en"),
    ("correction", "correction", "contains", "en"),
]

SQL_INSERT = "INSERT OR IGNORE INTO search_keywords (category, keyword, match_type, lang) VALUES (?, ?, ?, ?)"


def run(conn: sqlite3.Connection):
    conn.execute(SQL_CREATE)
    conn.execute(SQL_INDEX)
    conn.executemany(SQL_INSERT, SEED_DATA)
    conn.commit()
